[envs.reference]
command = "bril2json < {filename} | python3 ../examples/df.py defined"
# output.out-baseline = "-"

[envs.ours]
command = "bril2json < {filename} | python3 df.py"
# output.out-tdce = "-"
