extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}"
]

[runs.l3]
pipeline = [
    "bril2json",
    "python3 lvn.py",
    "bril2json",
    "python3 tdce.py",
    "bril2json",
    "brili -p {args}"
]

[runs.tdce]
pipeline = [
    "bril2json",
    "python3 tdce.py",
    "bril2json",
    "brili -p {args}",
]
